server:
  port: 18888

spring:
  application:
    name: jdbc
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    default-property-inclusion: non_null
    mapper:
      accept_case_insensitive_properties: true
    deserialization:
      fail-on-unknown-properties: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_demo?useUnicode=true&characterEncoding=utf-8&autoReconnectForPools=true&autoReconnect=true
    username: easeagent
    password: asdasd
    hikari:
      minimum-idle: 10
      maximum-pool-size: 15
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'


